### ISSUE TITLE
App does not read NFC

### ISSUE THREAD

**Issue by adnida** [don/ionic-nfc-reader#1]
Hi Don,

Thanks for making this example. I'm testing your code using google nexus 7 (ionic run --device), however, it does not seem to read the nfc, or display any feedback. Any idea why this is so? Thanks.

**Comment by don** [comment]
The app only reads NFC tags with NDEF messages.

Which Nexus 7? The original or the 2nd version? The 2nd release of the Nexus 7 won't read Mifare Classic tags, it only handles NFC Forum tags.

Can you read the data from the tags using an app like [NFC TagInfo by NXP](https://play.google.com/store/apps/details?id=com.nxp.taginfolite&hl=en)?

**Comment by vinimendes3** [comment]
Hello @don, I've tried with app NFC TagInfo by NXP and read the tag normally, but like @adnida, I can't read NFC tag. I'm trying with LG G3. I'm only trying to read the ID of the tag, and can't do this.

@adnida , you've solved the problem?

**Comment by don** [comment]
@adnida @vinimendes3 this issue is really old so I'm closing it. It's possible this was a permission issue if you're using Android 6. I edited config.xml to limit this code to android-22 to avoid that problem.
