### ISSUE TITLE
nfc not reading anything

### ISSUE THREAD

**Issue by r4mst3r** [don/ionic-nfc-reader#10]
Hi, I just pulled this remove with phgonegap plugin (v 0.6.6) for a nfc enabled ionic 1 application on my android onplus 3t phone.

I can hear the foreground of the nfc service on my phone making the sound and recognizing the tag but this demo does not recognize it. 

however my phone does auto detection to the tags and I downloaded NFC tools app from playstore and that too can read the tag im trying to get this reader demo to read.

im just trying to get the callbacks to fire but it doesnt seem to be firing at all!

**Comment by jayson-valentino** [comment]
I have the same problem.

**Comment by SkoZombie** [comment]
Same problem here. I'm going to work with my team to see if someone else can work out why it's not working properly

**Comment by 05akhiljain** [comment]
Same problem

**Comment by don** [comment]
Closing old issue. Reopen with more details if it's still a problem.
