### ISSUE TITLE
scan rfid card result not 10 digit number

### ISSUE THREAD

**Issue by sabardotnet** [don/ionic-nfc-reader#11]
how to make result like when we scan rfid with scanner, result 10 digit number. thanks
why my result like these picturre ? 
my code : 
			$scope.onNfc = function( nfcEvent )
			{
			console.log(nfcEvent);
			// display the tag as JSON
				var tag = nfcEvent.tag;
				var tagId = nfc.bytesToHexString(tag.id);
				alert(tagId);
			}			
			$scope.onNfcSuccess = function (result)
			{
				alert('NFC listening');
			}

			$scope.onNfcFail = function (result) {
				alert( 'NFC failed: ' + result );
			}
			nfc.addTagDiscoveredListener($scope.onNfc, $scope.onNfcSuccess, $scope.onNfcFail);		
		

![nfc](https://cloud.githubusercontent.com/assets/7982144/23028406/d04c4a68-f499-11e6-84ea-0c0d70f18b4f.jpg)

**Comment by don** [comment]
If you want the tag id, use [nfc.addTagDiscoveredListener](https://github.com/chariotsolutions/phonegap-nfc#nfcaddtagdiscoveredlistener). You'll get the tag id in the scan response. See the docs for more details about the [data in the tag event](https://github.com/chariotsolutions/phonegap-nfc#addtagdiscoveredlistener).
