### ISSUE TITLE
Writing to NFC Media

### ISSUE THREAD

**Issue by henrycjc** [don/ionic-nfc-reader#2]
Hi Don,

Thanks heaps for this example, it has helped me lots.

Just wondering though, is it possible to port the existing code in order to allow writing to the tags?

For example, on a ng-submit/ng-click event you could write the contents of the form as a specific type of NDEF message and then write it to a tag?

Thanks in advance!

**Comment by don** [comment]
This is a good idea. Unfortunately it may take a while before I get to this. In the mean time check out the docs for [nfc.write](https://github.com/chariotsolutions/phonegap-nfc/blob/master/README.md#nfcwrite).

Use that sample code inside the callback for nfc.addNdefListener. You may need another function to set the contents of the tag in the service.
