### ISSUE TITLE
Samsung s6 NFC tag type not supported

### ISSUE THREAD

**Issue by praveennishanth** [don/ionic-nfc-reader#6]
When I use a NFC tag my device is giving a warning text NFC tag type not supported how can i overcome this message. but the NFC tag is been read by the application and nfc-phonegap plugin. the NFC tag model used is "HID 1430 1L"
![screenshot_2016-01-29-19-49-46](https://cloud.githubusercontent.com/assets/16605377/12677884/e8fd9a64-c6c1-11e5-97b0-04d48663d4b0.png)  

These messages are coming in Sony mobiles as well.

**Comment by don** [comment]
Some phones don't support some types of NFC tags. It depends on the NFC hardware in the device.
