### ISSUE TITLE
Error on plugin add

### ISSUE THREAD

**Issue by julianlecalvez** [don/ionic-nfc-reader#7]
I have a simple ionic project, but I'm unable to install the plugin. It seems that the plugin is a PhoneGap one only. But this example is for ionic. What am I missing ?

```
$ cordova plugin add com.chariotsolutions.nfc.plugin
Error: Registry returned 404 for GET on https://registry.npmjs.org/com.chariotsolutions.nfc.plugin
```

**Comment by don** [comment]
The plugin id changed when things were moved to NPM. Try

```
cordova plugin add phonegap-nfc
```

**Comment by julianlecalvez** [comment]
Thanks ! it works !
But I tried 2 NFC tags, and it doesn't detect anything.
My tags are detected with this app: https://play.google.com/store/apps/details?id=com.nxp.taginfolite&hl=en
Here is a screenshot of the [tag detected](https://photos-6.dropbox.com/t/2/AABaVuPSSH_yXLv_57YWlG7leR5H_2mqA5yzaTysG3Iztw/12/127902408/png/32x32/3/1466035200/0/2/Screenshot_20160615-213234.png/ENu_vWIY6gMgAigC/-o5z-0V8h_z_by026IhVbw7XXzAztiX2yAv2Tp8izP0?size_mode=3&size=800x600)

So I guess it's another pb ?

**Comment by don** [comment]
That screenshot says your device doesn't support MifareClassic tags. (Since it has a Broadcom NFC chip.)

You need to get some NFC Forum Type 1,2,3 or 4 tags to use that phone.

Alternately you could try the code on an Android phone with the NXP NFC chip.

**Comment by julianlecalvez** [comment]
Mmmh ok ! Thanks !! 
I tried with a third kind of tag I have and it works, but i can't use them because they are not compatible with my arduino reader :(

Thanks for your help !!
