### ISSUE TITLE
cordova plugin add com.chariotsolutions.nfc.plugin

### ISSUE THREAD

**Issue by AMD-Roy** [don/ionic-nfc-reader#8]
error:registry returned 404 for get on https://registry.npmjs.org/com.chariotsolutions.nfc.plugin
so can't support ?   or other methed?

**Comment by aishahismail** [comment]
I got same error too.

**Comment by don** [comment]
The documentation needs to be updated. The plugin id changed when it moved from the Cordova repo to npm. 

```
$ cordova plugin add phonegap-nfc
```

**Comment by aishahismail** [comment]
@don I'm already added with `phonegap-nfc`, but when I scan using Mifare card, it didn't display any information.  It callback 'win' when call this event `nfc.addNdefListener(myNfcListener, win, fail);`. Thanks.

**Comment by don** [comment]
Documentation updated.

@aishahismail Android devices with Broadcom NFC chips don't support Mifare Classic NFC tags.
