### ISSUE TITLE
I can't read nfc card 

### ISSUE THREAD

**Issue by biy-gxnn** [don/ionic-nfc-reader#9]
I can't read nfc card with this app and the phone recommended other app when I crediting card. And I can read nfc card with recommended app

**Comment by gakuba** [comment]
I don't know what the problem but I can't read the card on samsung note 7

**Comment by gakuba** [comment]
May it has something to do with Ionic 2. do you I need to strictly  use 1.X  ?

**Comment by tddawson** [comment]
Not sure if this will fix it for you, but I would use one of the other apps to see what format the tag you're trying to read is. This sample code only adds a `addNdefListener`. I was using a tag with NfcV and NdefFormatable technologies and it wasn't being recognized. Instead, I used the more generic `addTagDiscoveredListener` and it worked just fine. (https://github.com/chariotsolutions/phonegap-nfc#nfcaddtagdiscoveredlistener)

**Comment by tomitbe** [comment]
I am also using ionic2 and I am not able to trigger the listener, my sample code:

import {NFC, Ndef} from 'ionic-native';

export class AppComponent {
  rootPage: any;  
  public translatedText: string;
  public supportedLangs: any[];
  
  constructor(platform: Platform,translate: TranslateService) {   
   
    this.rootPage = Meteor.user() ? navComponent : LoginComponent;        

    platform.ready().then(() => {
      NFC.addTagDiscoveredListener('text/plain',(nfcEvent) => {
                console.log("success" + JSON.stringify(nfcEvent.tag, null, 4));               
            }, (fail) => {
                console.log("failed for NDEF Tags." + fail);
            });

      StatusBar.styleDefault();
    });
  }
}

@don  hope you can help the Ionic2 users :-)

**Comment by don** [comment]
This app is just Ionic1. Ionic2 is different enough that it needs a new demo. The Ionic native wrapper might help https://ionicframework.com/docs/v2/native/nfc/
